# Copyright Ben Paul Wise. All Rights Reserved.
"""trc_startline.py -- re-derive the 1941 start line of games/trc/scenario/trc-1941.xml from the sheet.

    python trc_startline.py SHEET.xml COUNTERS.xml SCENARIO.xml            report only
    python trc_startline.py SHEET.xml COUNTERS.xml SCENARIO.xml --write    rewrite units and control hexes

The rule the scenario's notes state. No input carries the hexes of the set-up areas, so:
  1. every land hex takes the side of its nearest anchor city by hop distance over the whole grid (Axis
     anchors win ties), as trc_control.py measures it;
  2. a unit whose back names a city stands on that city's hex;
  3. a unit whose back names an area (army group, military district, country) stands on its side's front
     hexes (own-side land hexes next to an enemy-side land hex) nearest the area's anchor city, stacked
     legally (6.1: three corps or two armies; a mixed stack two; no-value units free);
  4. the control list names every city, oil field and rail junction with the side of its hex.
The rail link control list is then regenerated by trc_control.py. Rerun both whenever the sheet's cities,
terrain or rail change, then re-record the TRC goldens.
"""
import collections
import re
import sys

from lxml import etree

import trc_control as C

# set-up area (as the counter back names it) -> anchor city (as the sheet names it)
AREA_ANCHOR = {"AGN": "Königsberg", "AGC": "WARSAW", "AGS": "Breslau", "Rumania": "BUCHAREST",
               "Finland": "HELSINKI", "Baltic MD": "Kaunas", "Western MD": "Brest", "Kiev MD": "Lvov",
               "Odessa MD": "ODESSA", "Finnish Border": "LENINGRAD"}
NO_VALUE_TYPES = {"hq", "leader", "worker", "partisan"}
UNIT = re.compile(r'(<unit id="([^"]+)" counter="([^"]+)" type="([^"]+)" owner="([a-z]+)") hex="([^"]*)"'
                  r'((?:/>)|(?:>([^<]*)</unit>))')


def land_hexes(sheet):
    wet = set()
    for hs in sheet.root.findall("hexes"):
        if hs.get("terrain") in ("sea", "lake"):
            wet |= set(hs.get("ids").split())
    return {h for h in sheet.cell if h not in wet}


def hops(sheet, start, land):
    dist = {start: 0}
    queue = collections.deque([start])
    while queue:
        h = queue.popleft()
        for _, n in sheet.neighbours(h):
            if n in land and n not in dist:
                dist[n] = dist[h] + 1
                queue.append(n)
    return dist


def echelons(counters_path):
    root = etree.parse(counters_path).getroot()
    out = {}
    for c in root.iter("counter"):
        e = c.find(".//echelon")
        out[c.get("id")] = e.get("level") if e is not None else None
    return out


def weight(unit_type, counter, level):
    """Stacking size: None for no stacking value, else 'corps' or 'army'."""
    if unit_type in NO_VALUE_TYPES or counter == "g-ss-res-infantry":
        return None
    if level not in ("corps", "army"):
        raise SystemExit("counter %s has no corps/army echelon (%s)" % (counter, level))
    return level


def fits(stack, level):
    sizes = [s for s in stack if s is not None] + [level]
    if "army" in sizes:
        return len(sizes) <= 2
    return len(sizes) <= 3


def derive(sheet, counters_path, text):
    names = {h.get("name"): h.get("id") for h in sheet.root.findall("hex") if h.get("name")}
    land = land_hexes(sheet)
    anchors = [(names[n], "axis") for n in C.AXIS] + [(names[n], "russian") for n in C.RUSSIAN]
    dists = [C.hops_from(sheet, a) for a, _ in anchors]  # whole grid, as trc_control.py measures
    far = 10 ** 6
    side = {h: anchors[min(range(len(anchors)), key=lambda k: (dists[k].get(h, far), k))][1] for h in land}
    front = {h for h in land if any(n in land and side[n] != side[h] for _, n in sheet.neighbours(h))}
    level = echelons(counters_path)
    stacks = collections.defaultdict(list)
    placed = {}
    by_name = {n.lower(): h for n, h in names.items()}
    for m in UNIT.finditer(text):
        uid, counter, utype, owner, back = m.group(2), m.group(3), m.group(4), m.group(5), (m.group(8) or "").strip()
        size = weight(utype, counter, level.get(counter))
        if back.lower() in by_name and back not in AREA_ANCHOR:  # a city
            hexid = by_name[back.lower()]
        elif back in AREA_ANCHOR:
            a = names[AREA_ANCHOR[back]]
            da = hops(sheet, a, land)
            candidates = sorted((h for h in front if side[h] == owner and h in da), key=lambda h: (da[h], h))
            hexid = next((h for h in candidates if size is None or fits(stacks[h], size)), None)
            if hexid is None:
                raise SystemExit("no legal front hex for %s (%s)" % (uid, back))
        else:
            raise SystemExit("unit %s: back %r names neither a city nor an area" % (uid, back))
        stacks[hexid].append(size)
        placed[uid] = hexid
    control = {}
    for h in sheet.root.findall("hex"):
        if h.get("name") and h.get("id") in side:
            control[h.get("id")] = side[h.get("id")]
    rail = collections.Counter()
    for l in sheet.root.findall("link"):
        if l.get("kind") == "rail":
            hs = l.get("hexes").split()
            for a, b in zip(hs, hs[1:]):
                rail[a] += 1
                rail[b] += 1
    for h, n in rail.items():
        if n >= 3 and h in side:
            control[h] = side[h]
    return placed, control


def rewrite(text, placed, control):
    def unit(m):
        return '%s hex="%s"%s' % (m.group(1), placed[m.group(2)], m.group(7))
    text = UNIT.sub(unit, text)
    i = text.index("<control>")
    j = text.index('    <link network="rail"', i) if '<link network="rail"' in text[i:] else text.index("</control>", i)
    order = sorted(control, key=lambda h: (len(re.match(r"[A-Z]+", h).group(0)), h))
    body = "".join('    <hex id="%s" side="%s"/>\n' % (h, control[h]) for h in order)
    return text[:i] + "<control>\n" + body + text[j:]


def main(argv):
    if len(argv) < 4:
        print(__doc__)
        return 2
    sheet = C.Sheet(argv[1])
    text = open(argv[3], encoding="utf-8").read()
    placed, control = derive(sheet, argv[2], text)
    old = {m.group(2): m.group(6) for m in UNIT.finditer(text)}
    moved = sum(1 for u in placed if placed[u] != old[u])
    print("units %d, moved %d; control hexes %d" % (len(placed), moved, len(control)))
    if "--write" in argv:
        with open(argv[3], "w", encoding="utf-8", newline="\n") as f:
            f.write(rewrite(text, placed, control))
        print("wrote", argv[3])
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
# Copyright Ben Paul Wise. All Rights Reserved.
