// Copyright Ben Paul Wise. All Rights Reserved.
#include "mcpengines.hpp"
#include "saoe.hpp"
#include "saoesupport.hpp"
#include "utils.hpp"

#include <Eigen/Dense>
#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <numeric>
#include <random>
#include <stdexcept>
#include <vector>

using namespace VINCP;

// ============================================================================
// The alternating chain pointed at the SAOE equilibrium-selection problem --
// the library's oldest open item: on the reduced effort-space formulation
// (saoe.hpp), the Josephy-Newton engines reliably converge to a
// negative-utility KKT point rather than the reference equilibrium E that
// PATH, NPLEC, and the earlier C++ implementation all find, and every start
// tried has fallen into that same wrong basin. The chain -- with the
// globalize/finish alternation and the perturb-restart sampler that found a
// second equilibrium on the deployment game -- is the designated candidate
// for reaching E.
//
// Two instances:
//  (1) REFERENCE: the standard 6-actor x 10-option instance of saoe_test /
//      alloceff01cm.gms, whose reference equilibrium E is known and
//      author-verified. Gate: the chain converges AND lands on E
//      (feasibility + RMSE, the same bars saoe_test uses). This is the
//      equilibrium-selection experiment itself; a converged run in a
//      different basin fails the gate honestly and prints itself.
//  (2) EXPANDED (performance): a seeded 20-actor x 12-option instance
//      generated by the constrained recipe below (no known equilibrium).
//      Gate: the chain converges to a feasible allocation. Timing comes
//      from the runCase harness.
//
// Expanded-instance generation (kSaoeExpandedSeed): rewards R (20 x 12) drawn
// U[-50, 100] with EXACTLY one third of the entries zero (80 of 240),
// subject to: every column has at least one negative and at least one
// positive entry; every row has at least two positive and at least two
// negative entries. Strengths S ~ U[10, 100]. The generator enforces the
// row quota by construction (two slots per row forced to each sign) and
// the column quota by targeted redraws of unforced slots, restarting from
// a fresh zero mask in the (never observed) case where repair is
// impossible; the test re-verifies every constraint on the finished matrix.
// ============================================================================


// The equilibrium-selection experiment: from the deterministic default start
// (the one that has always led the JN engines into the wrong basin), the
// chain must converge AND land on the reference equilibrium E.
TEST(SaoeChain, ReferenceInstanceReachesKnownEquilibrium) {
    MatrixXd R, E;
    VectorXd S;
    saoeReferenceInstance(R, S, E);
    saoePrintInputs(R, S, /*latex=*/false);

    const VIModel  model = saoeModel(R, S);
    const VectorXd z0    = saoeDefaultStart(R, S);
    const SolveFn  chain = makeSaoeChain(model);

    const int failures = runCase("saoe-chain (reference 6x10)", chain, z0,
                                 { saoePrintDecoded(R), saoeCheckFeasible(R, S),
                                   saoeCheckMatchesReference(E),
                                   checkConvergedFlag() });
    EXPECT_EQ(0, failures)
        << "the alternating chain did not reach the reference equilibrium E "
           "on the 6x10 SAOE instance";
}

// The performance instance: seeded 20 x 12, generated under the sign-quota
// recipe (re-verified here), no known equilibrium. Gate: converge to a
// feasible allocation; the runCase harness prints the timing.
TEST(SaoeChain, ExpandedInstanceConverges) {
    const MatrixXd R = saoeMakeExpandedRewards(kSaoeExpandedSeed);
    const VectorXd S = saoeMakeExpandedStrengths(kSaoeExpandedSeed);

    // Re-verify every generator postcondition on the finished matrix.
    int zeros = 0;
    for (Index i = 0; i < kSaoeExpActors; ++i) {
        int rowPos = 0, rowNeg = 0;
        for (Index j = 0; j < kSaoeExpOptions; ++j) {
            const double v = R(i, j);
            zeros  += (0.0 == v) ? 1 : 0;
            rowPos += (0.0 < v) ? 1 : 0;
            rowNeg += (v < 0.0) ? 1 : 0;
            EXPECT_TRUE(kSaoeRewardLo <= v && v <= kSaoeRewardHi);
        }
        EXPECT_GE(rowPos, kSaoeRowPosQuota) << "row " << i;
        EXPECT_GE(rowNeg, kSaoeRowPosQuota) << "row " << i;
    }
    EXPECT_EQ(kSaoeExpZeros, zeros);
    for (Index j = 0; j < kSaoeExpOptions; ++j) {
        int colPos = 0, colNeg = 0;
        for (Index i = 0; i < kSaoeExpActors; ++i) {
            colPos += (0.0 < R(i, j)) ? 1 : 0;
            colNeg += (R(i, j) < 0.0) ? 1 : 0;
        }
        EXPECT_GE(colPos, kSaoeColPosQuota) << "column " << j;
        EXPECT_GE(colNeg, kSaoeColPosQuota) << "column " << j;
    }
    for (Index i = 0; i < kSaoeExpActors; ++i) {
        EXPECT_TRUE(kSaoeStrengthLo <= S(i) && S(i) <= kSaoeStrengthHi) << "strength " << i;
    }

    saoePrintInputs(R, S, /*latex=*/false);

    const VIModel  model = saoeModel(R, S);
    const VectorXd z0    = saoeDefaultStart(R, S);
    const SolveFn  chain = makeSaoeChain(model);

    const int failures = runCase("saoe-chain (expanded 20x12)", chain, z0,
                                 { saoePrintDecoded(R), saoeCheckFeasible(R, S),
                                   checkConvergedFlag() });
    EXPECT_EQ(0, failures)
        << "the alternating chain did not converge to a feasible allocation "
           "on the expanded 20x12 SAOE instance";
}
// Copyright Ben Paul Wise. All Rights Reserved.
