"""
compete.py
----------------------------------------------------------------------
Runs the two illustrations of the paper against the two methods a
reader is most likely to name as alternatives: the lasso, and
stochastic search variable selection.

The data are generated by sweep.build, call for call, so every method
sees exactly the same matrices, the same inputs and the same errors.
The comparison is therefore paired at the level of the seed and at the
level of the case.

Six procedures are compared.  The rows are separate regressions, so
each lasso variant chooses its penalty row by row.

  mple          the procedure of the paper: the pattern chosen by
                minimising Phi, the coefficients then moved to the
                stationary point of the posterior

  lasso-cv      penalty chosen by leave-one-out cross-validation; this
                is what an analyst without a noise estimate would do

  lasso-bic     penalty chosen by minimising the residual sum of
                squares divided by the true error variance, plus the
                number of occupied cells times the logarithm of the
                number of observations; this is the Schwarz criterion,
                and it is given the true error scale, which no analyst
                would have

  alasso-bic    the adaptive lasso, penalising each cell in inverse
                proportion to its magnitude in the lasso-bic fit, with
                the penalty chosen by the same criterion

  lasso-best    penalty chosen row by row by counting the pattern
                errors against the truth and taking the penalty that
                makes them fewest; no analyst can do this, since it
                requires the answer, and it is included only as a bound
                on what any choice of penalty could achieve

  ssvs          the two-component normal prior of George and McCulloch,
                with a Bernoulli prior on the indicators, a uniform
                hyper-prior on the occupancy rate, and one error scale
                for the whole matrix; the pattern is the median
                probability model

The lasso and ssvs both return shrunken coefficients, so their
coefficients are refitted by least squares on the pattern they select
before the Frobenius error is computed.  Without that step the
comparison would charge them for shrinkage rather than for the pattern,
and the pattern is what is at issue.  The unrefitted figure is reported
alongside for the lasso.
----------------------------------------------------------------------
"""

import sys
import numpy as np
from math import log, sqrt
from scipy.linalg import cho_factor, cho_solve

import sweep
from sweep import N, T, n, q, SIGMA_TRUE, build, logdets, analyse

# ---------------------------------------------------------------- lasso

NLAM = 100                      # points on the penalty path
NFOLDS = 10                     # cross-validation folds, or T if T is smaller
LAMRATIO = 1.0e-3               # smallest penalty as a fraction of the largest
CDITERS = 2000
CDTOL = 1.0e-10


def standardise(Z):
    """Scale the columns to unit length, as the lasso convention requires.

    The penalty treats every column alike, so the columns must be on one
    scale before it is applied.  The scaling is undone on the way out.
    """
    nrm = np.sqrt(np.sum(Z * Z, axis=0))
    nrm[nrm == 0.0] = 1.0
    return Z / nrm, nrm


def lasso_path(Z, y, lams):
    """Coordinate descent for the whole path, warm started downwards.

    Minimises one half the residual sum of squares plus lam times the
    sum of absolute coefficients.  The problem is small enough that
    plain coordinate descent is exact for practical purposes.
    """
    p = Z.shape[1]
    zz = np.sum(Z * Z, axis=0)
    a = np.zeros(p)
    out = np.empty((len(lams), p))
    r = y.copy()
    for k, lam in enumerate(lams):
        for _ in range(CDITERS):
            biggest = 0.0
            for j in range(p):
                if zz[j] == 0.0:
                    continue
                aj = a[j]
                rho = float(Z[:, j] @ r) + zz[j] * aj
                new = np.sign(rho) * max(abs(rho) - lam, 0.0) / zz[j]
                if new != aj:
                    r -= Z[:, j] * (new - aj)
                    a[j] = new
                    biggest = max(biggest, abs(new - aj))
            if biggest < CDTOL:
                break
        out[k] = a
    return out


def row_lams(Zs, y):
    """The penalty grid for one row.

    It runs from the smallest penalty that empties the row down to a
    thousandth of it, which covers everything from the empty pattern to
    a fit that interpolates the six observations.
    """
    lam_max = float(np.max(np.abs(Zs.T @ y)))
    return np.exp(np.linspace(log(lam_max), log(lam_max * LAMRATIO), NLAM))


def lasso_row_variants(X, y, a_true_row):
    """Every lasso variant for one row, returned as coefficient vectors.

    The row is a regression of six observations on nine candidates, so
    the four variants differ only in how the penalty is chosen: by
    cross-validation, by the Schwarz criterion with the true error
    scale, by the same criterion after reweighting, and by counting the
    errors against the truth.
    """
    Z = X.T
    Zs, nrm = standardise(Z)
    lams = row_lams(Zs, y)
    path = lasso_path(Zs, y, lams)              # in standardised units

    # cross-validation, in min(10, T) folds
    #
    # Leaving out one observation at a time is the only choice when T is
    # six, and it is what this reduces to there, since ten folds cannot
    # be cut from six points.  At larger T it refits the path once per
    # fold rather than once per observation, which is the usual practice
    # and costs a fraction as much.
    cv = np.zeros(NLAM)
    for fold in np.array_split(np.arange(T), min(NFOLDS, T)):
        keep = np.setdiff1d(np.arange(T), fold)
        co = lasso_path(Zs[keep, :], y[keep], lams)
        cv += np.sum((co @ Zs[fold, :].T - y[fold]) ** 2, axis=1)

    # the Schwarz criterion, given the true error scale
    resid = y[None, :] - path @ Zs.T
    rss = np.sum(resid * resid, axis=1)
    nz = np.sum(path != 0.0, axis=1)
    bic = rss / (SIGMA_TRUE ** 2) + nz * log(n)

    # the penalty that makes the fewest pattern errors
    tru = a_true_row != 0.0
    hit = path != 0.0
    errs = np.sum(hit & ~tru, axis=1) + np.sum(~hit & tru, axis=1)

    out = {"lasso-cv": path[int(np.argmin(cv))] / nrm,
           "lasso-bic": path[int(np.argmin(bic))] / nrm,
           "lasso-best": path[int(np.argmin(errs))] / nrm}

    # the adaptive lasso, weighted by the lasso-bic fit
    init = np.abs(out["lasso-bic"])
    w = 1.0 / np.maximum(init, 0.05)
    Zw = Zs / w
    lam_w = row_lams(Zw, y)
    path_w = lasso_path(Zw, y, lam_w) / w
    resid = y[None, :] - path_w @ Zs.T
    rss = np.sum(resid * resid, axis=1)
    nz = np.sum(path_w != 0.0, axis=1)
    bic_w = rss / (SIGMA_TRUE ** 2) + nz * log(n)
    out["alasso-bic"] = path_w[int(np.argmin(bic_w))] / nrm

    return out


# ----------------------------------------------------------------- ssvs

SSVS_TAU0 = 0.02                # standard deviation of the spike
SSVS_TAU1 = 1.50                # standard deviation of the slab
SSVS_DRAWS = 20000
SSVS_BURN = 5000
SSVS_A0 = 0.001                 # inverse gamma shape for the error variance
SSVS_B0 = 0.001


def ssvs(X, Y, seed, tau0=SSVS_TAU0, tau1=SSVS_TAU1,
         draws=SSVS_DRAWS, burn=SSVS_BURN):
    """Stochastic search variable selection, in the form of George and
    McCulloch, with one error scale and one occupancy rate shared by the
    whole matrix.

    Every coefficient is drawn from one of two normal distributions, a
    narrow one centred at zero for cells that are to be treated as
    empty, and a wide one for cells that are to be treated as occupied.
    The indicator saying which is drawn along with everything else.
    """
    rng = np.random.default_rng(seed)
    Z = X.T                                     # T by N
    ZtZ = Z.T @ Z
    Zty = np.array([Z.T @ Y[i] for i in range(N)])

    A = np.zeros((N, N))
    gam = np.zeros((N, N), dtype=bool)
    sig2 = float(SIGMA_TRUE ** 2)
    p = 0.5

    pip = np.zeros((N, N))
    kept = 0

    v0, v1 = tau0 * tau0, tau1 * tau1
    half_log_ratio = 0.5 * log(v0 / v1)

    for it in range(draws):
        # the coefficients, row by row
        for i in range(N):
            dinv = np.where(gam[i], 1.0 / v1, 1.0 / v0)
            prec = ZtZ / sig2 + np.diag(dinv)
            # The precision is positive definite by construction, so its
            # inverse is obtained from a Cholesky factor.  This gives the
            # same matrix as a general inverse, to the last bit, and on
            # this machine it is some fifty times faster at N = 200,
            # where numpy's general inverse is unaccountably slow.
            cov = cho_solve(cho_factor(prec), np.eye(N))
            mu = cov @ (Zty[i] / sig2)
            L = np.linalg.cholesky((cov + cov.T) * 0.5)
            A[i] = mu + L @ rng.standard_normal(N)

        # the indicators
        lodds = (log(p) - log(1.0 - p) + half_log_ratio
                 + 0.5 * A * A * (1.0 / v0 - 1.0 / v1))
        gam = rng.random((N, N)) < 1.0 / (1.0 + np.exp(-np.clip(lodds, -500, 500)))

        # the occupancy rate
        M = int(np.sum(gam))
        p = float(rng.beta(1.0 + M, 1.0 + q - M))
        p = min(max(p, 1.0e-6), 1.0 - 1.0e-6)

        # the error scale
        Rm = Y - A @ X
        R = float(np.sum(Rm * Rm))
        sig2 = float(1.0 / rng.gamma(SSVS_A0 + 0.5 * n, 1.0 / (SSVS_B0 + 0.5 * R)))

        if it >= burn:
            pip += gam
            kept += 1

    return pip / kept


# -------------------------------------------------------------- scoring


def refit(X, Y, mask):
    """Least squares on the pattern that was selected.

    A row whose pattern has more cells than there are observations has
    no unique least-squares fit; the minimum-norm solution is taken, and
    such rows are counted, since they are a defect of the pattern and
    not of the arithmetic.
    """
    A = np.zeros((N, N))
    over = 0
    for i in range(N):
        cols = np.where(mask[i])[0]
        if cols.size == 0:
            continue
        if cols.size > T:
            over += 1
        Xs = X[cols, :]
        c, *_ = np.linalg.lstsq(Xs.T, Y[i], rcond=None)
        A[i, cols] = c
    return A, over


def score(A, mask, A_true, X, Y):
    tru = A_true != 0.0
    M = int(np.sum(mask))
    R = float(np.sum((Y - A @ X) ** 2))
    return dict(M=M,
                correct=int(np.sum(mask & tru)),
                false=int(np.sum(mask & ~tru)),
                missed=int(np.sum(~mask & tru)),
                sigma=float(sqrt(R / max(n - M, 1))),
                frob=float(sqrt(np.sum((A - A_true) ** 2))))


# ------------------------------------------------------------------ run


def one_case(X, Y, A_true, slds, seed):
    out = {}

    # the procedure of the paper
    r = analyse(X, Y, A_true, slds)
    out["mple"] = r

    # the lasso variants, row by row
    raw = {tag: np.zeros((N, N)) for tag in LASSOS}
    for i in range(N):
        vs = lasso_row_variants(X, Y[i], A_true[i])
        for tag in LASSOS:
            raw[tag][i] = vs[tag]

    for tag in LASSOS:
        mask = raw[tag] != 0.0
        A_ref, over = refit(X, Y, mask)
        s = score(A_ref, mask, A_true, X, Y)
        s["frob_raw"] = float(sqrt(np.sum((raw[tag] - A_true) ** 2)))
        s["over"] = over
        out[tag] = s

    # stochastic search variable selection
    pip = ssvs(X, Y, seed)
    mask = pip >= 0.5
    A_ref, over = refit(X, Y, mask)
    s = score(A_ref, mask, A_true, X, Y)
    s["over"] = over
    out["ssvs"] = s

    return out


LASSOS = ["lasso-cv", "lasso-bic", "alasso-bic", "lasso-best"]
METHODS = ["mple"] + LASSOS + ["ssvs"]

# The names used in the document, which say what each variant is rather
# than what it is called in the code.
LABEL = {"mple": "this paper",
         "lasso-cv": "lasso, cross-validated",
         "lasso-bic": "lasso, Schwarz, true $\\sigma$",
         "alasso-bic": "adaptive lasso, Schwarz",
         "lasso-best": "lasso, penalty from the answer",
         "ssvs": "SSVS"}


# --------------------------------------------------------------- tables


def sign_test(a, b):
    """Two-sided sign test on the paired counts a and b.

    Ties carry no information about direction and are excluded, which is
    what the test requires.
    """
    from math import comb
    d = a + b
    if d == 0:
        return 1.0
    tail = sum(comb(d, i) for i in range(min(a, b) + 1))
    return min(1.0, 2.0 * tail / 2.0 ** d)


def fmt_p(p):
    """A p-value in the form the document uses."""
    if p >= 0.001:
        return f"${p:.2f}$"
    e = 0
    while p < 1.0:
        p *= 10.0
        e += 1
    return f"$%d \\times 10^{{-%d}}$" % (round(p), e)


def write_tables(rows):
    """The two summary tables, as the document reads them.

    They are produced here rather than typed into the document, so that
    re-running this script cannot leave the two disagreeing.
    """
    key = lambda r: (r["seed"], r["case"])
    by = {}
    for r in rows:
        by.setdefault(r["method"], {})[key(r)] = r
    ks = sorted(by["mple"])

    out = ["\\begin{center}", "\\footnotesize",
           "\\begin{tabular}{llccccc}",
           "case & method & correct of 27 & false & missed & exact"
           " & median $\\hat\\sigma$ \\\\",
           "\\hline"]
    for case in ("block", "scatter"):
        if case == "scatter":
            out.append("\\hline")
        for m in METHODS:
            rs = [r for r in rows if r["case"] == case and r["method"] == m]
            corr = np.mean([r["correct"] for r in rs])
            fal = np.mean([r["false"] for r in rs])
            mis = np.mean([r["missed"] for r in rs])
            ex = sum(1 for r in rs if r["false"] == 0 and r["missed"] == 0)
            sg = np.median([r["sigma"] for r in rs])
            out.append(f"{case} & {LABEL[m]} & ${corr:.2f}$ & ${fal:.2f}$"
                       f" & ${mis:.2f}$ & ${ex}$ of ${len(rs)}$"
                       f" & ${sg:.3f}$ \\\\")
    out += ["\\end{tabular}", "\\end{center}", ""]
    with open("tab_compete.tex", "w") as f:
        f.write("\n".join(out))

    err = lambda r: r["false"] + r["missed"]
    out = ["\\begin{center}", "\\footnotesize",
           "\\begin{tabular}{lcccc}",
           "method & worse & better & equal & sign test \\\\",
           "\\hline"]
    for m in METHODS[1:]:
        w = sum(1 for k in ks if err(by[m][k]) > err(by["mple"][k]))
        b = sum(1 for k in ks if err(by[m][k]) < err(by["mple"][k]))
        e = len(ks) - w - b
        out.append(f"{LABEL[m]} & ${w}$ & ${b}$ & ${e}$"
                   f" & {fmt_p(sign_test(w, b))} \\\\")
    out += ["\\end{tabular}", "\\end{center}",
            f"% {len(ks)} paired comparisons, "
            f"errors counted as false plus missed", ""]
    with open("tab_compete_paired.tex", "w") as f:
        f.write("\n".join(out))


def read_rows(path="compete.txt"):
    """Recovers the per-trial results already written, so that the
    tables can be rebuilt without repeating the whole run."""
    rows = []
    for ln in open(path):
        p = ln.split()
        if len(p) == 9 and p[0].isdigit():
            rows.append(dict(seed=int(p[0]), case=p[1], method=p[2],
                             M=int(p[3]), correct=int(p[4]), false=int(p[5]),
                             missed=int(p[6]), sigma=float(p[7]),
                             frob=float(p[8])))
    return rows


def main(nseeds):
    seeds = [20260726] + [20260726 + 1000 * i for i in range(1, nseeds)]
    rows = []

    hdr = (f"{'seed':>10}  {'case':<8} {'method':<11} {'M':>3} {'corr':>5}"
           f" {'false':>6} {'miss':>5} {'sigma':>7} {'frob':>7}")
    print(hdr)
    for s in seeds:
        A_block, A_scatter, X, E = build(s)
        slds = logdets(X)
        for name, A_true in (("block", A_block), ("scatter", A_scatter)):
            Y = A_true @ X + E
            res = one_case(X, Y, A_true, slds, s)
            for m in METHODS:
                r = dict(res[m])
                r.update(seed=s, case=name, method=m)
                rows.append(r)
                print(f"{s:>10}  {name:<8} {m:<11} {r['M']:3d} {r['correct']:5d}"
                      f" {r['false']:6d} {r['missed']:5d} {r['sigma']:7.4f}"
                      f" {r['frob']:7.3f}")
        sys.stdout.flush()

    lines = []
    lines.append(f"seeds={len(seeds)} N={N} T={T} sigma_true={SIGMA_TRUE}")
    lines.append(f"ssvs tau0={SSVS_TAU0} tau1={SSVS_TAU1} "
                 f"draws={SSVS_DRAWS} burn={SSVS_BURN}")
    lines.append("")
    lines.append(f"{'case':<8} {'method':<11} {'correct':>8} {'false':>7}"
                 f" {'missed':>7} {'exact':>6} {'med sig':>8} {'med frob':>9}")
    for case in ("block", "scatter"):
        for m in METHODS:
            rs = [r for r in rows if r["case"] == case and r["method"] == m]
            corr = np.array([r["correct"] for r in rs], float)
            fal = np.array([r["false"] for r in rs], float)
            mis = np.array([r["missed"] for r in rs], float)
            sg = np.array([r["sigma"] for r in rs], float)
            fb = np.array([r["frob"] for r in rs], float)
            exact = int(np.sum((fal == 0) & (mis == 0)))
            lines.append(f"{case:<8} {m:<11} {corr.mean():8.2f} {fal.mean():7.2f}"
                         f" {mis.mean():7.2f} {exact:4d}/{len(rs):<2d}"
                         f" {np.median(sg):8.4f} {np.median(fb):9.3f}")
        lines.append("")

    # paired comparison against the procedure of the paper, over both cases
    lines.append("paired against mple, both cases pooled "
                 "(errors = false + missed)")
    key = lambda r: (r["seed"], r["case"])
    base = {key(r): r for r in rows if r["method"] == "mple"}
    for m in METHODS[1:]:
        other = {key(r): r for r in rows if r["method"] == m}
        e = lambda r: r["false"] + r["missed"]
        worse = sum(1 for k in base if e(other[k]) > e(base[k]))
        better = sum(1 for k in base if e(other[k]) < e(base[k]))
        same = len(base) - worse - better
        lines.append(f"  {m:<11} worse than mple {worse:3d}   "
                     f"better {better:3d}   equal {same:3d}   of {len(base)}")
    lines.append("")

    over = sum(r.get("over", 0) for r in rows)
    lines.append(f"rows selected with more cells than observations: {over}")

    text = "\n".join(lines)
    print("\n---------------- summary ----------------")
    print(text)
    write_tables(rows)
    with open("compete.txt", "w") as f:
        f.write(text + "\n\n")
        f.write(f"{'seed':>10} {'case':<8} {'method':<11} "
                f"{'M':>3} {'corr':>5} {'false':>6} {'miss':>5} "
                f"{'sigma':>7} {'frob':>7}\n")
        for r in rows:
            f.write(f"{r['seed']:>10} {r['case']:<8} {r['method']:<11} "
                    f"{r['M']:3d} {r['correct']:5d} {r['false']:6d} "
                    f"{r['missed']:5d} {r['sigma']:7.4f} {r['frob']:7.3f}\n")


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--tables":
        write_tables(read_rows())
        print("tab_compete.tex and tab_compete_paired.tex rebuilt "
              "from compete.txt")
    else:
        main(int(sys.argv[1]) if len(sys.argv) > 1 else 40)
